openapi: 3.0.0
info:
  title: Asset Management API
  description: API for managing assets, users, and cryptocurrency values.
  version: 1.0.0
servers:
  - url: http://localhost:3000/
    description: Development server
paths:
  /login:
    post:
      summary: Authenticate user and provide a JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful, JWT provided.
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '401':
          description: Unauthorized, user does not exist or invalid password.

  /signup:
    post:
      summary: Register a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        '201':
          description: User created successfully.
        '400':
          description: Bad request, user already exists.
        '500':
          description: Internal server error.

  /assets:
    get:
      summary: Get a list of in-use assets.
      responses:
        '200':
          description: Successfully retrieved assets.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
        '500':
          description: Internal server error.

  /assets/all:
    get:
      summary: Get a list of all assets.
      responses:
        '200':
          description: Successfully retrieved all assets.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties:
                    type: string
        '500':
          description: Internal server error.

  /asset/{id}:
    post:
      summary: Add an asset to in-use list.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Asset added successfully.
        '400':
          description: Resource not added, something went wrong.
    delete:
      summary: Delete an asset from in-use list.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Resource deleted successfully.
        '500':
          description: Internal server error.

components:
  securitySchemes:
    cookieAuth:
      type: cookie
      in: header
      name: token